# NAME: Priyanshu Patel
# PRN: 8034

In [455]:
import pandas as pd
import numpy as np

1. Write a Pandas program to create and display a one-dimensional array-like
object containing an array of data using Pandas module.

In [456]:
a=pd.Series([1,23,4,5,7,12])
a

0     1
1    23
2     4
3     5
4     7
5    12
dtype: int64

2. Write a Pandas program to convert a Panda module Series to Python list
and it's type.

In [457]:
b=a.to_list()
print(type(b))

<class 'list'>

3. Write a Pandas program to add, subtract, multiple and divide two Pandas
Series

In [458]:
b=pd.Series(np.random.randint(1,50,6))
print(a+b,a-b,a*b,(a/b).round(2),sep='\n')

0    23
1    64
2    31
3    21
4    24
5    26
dtype: int64
0   -21
1   -18
2   -23
3   -11
4   -10
5    -2
dtype: int64
0     22
1    943
2    108
3     80
4    119
5    168
dtype: int64
0    0.05
1    0.56
2    0.15
3    0.31
4    0.41
5    0.86
dtype: float64

4. Write a Pandas program to compare the elements of the two Pandas
Series

In [459]:
print(a>b,a<b,a>=b,a<=b,sep='\n')

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool

5. Write a Pandas program to convert a dictionary to a Pandas series.

In [460]:
a=pd.Series({'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
)
a

a    100
b    200
c    300
d    400
e    800
dtype: int64

6. Write a Pandas program to convert a NumPy array to a Pandas series.

In [461]:
b=pd.Series(np.random.randint(1,50,6))
b

0     9
1    38
2     6
3    23
4    45
5    13
dtype: int32

7. Write a Pandas program to change the data type of given a column or a
Series.

In [462]:
a=pd.Series([1,np.nan,32,np.nan,52,88,'abc',np.inf])
a=pd.to_numeric(a,errors='coerce')
a

0     1.0
1     NaN
2    32.0
3     NaN
4    52.0
5    88.0
6     NaN
7     inf
dtype: float64

8. Write a Pandas program to convert the first column of a DataFrame as a
Series.

In [463]:
a=np.random.randint(20,150,(6,3))
df=pd.DataFrame(a,columns=['Col1','Col2','Col3'])
df.Name='Original DataFrame'
df

   Col1  Col2  Col3
0    77    36    67
1    82    55    49
2    21    87   116
3    52   134    64
4    52    84    37
5   115   131   114

In [464]:
s1=pd.Series(df['Col1'],name='As Series')
s1

0     77
1     82
2     21
3     52
4     52
5    115
Name: As Series, dtype: int32

9. Write a Pandas program to convert a given Series to an array.

In [465]:
s1=s1.to_numpy()
print(type(s1),s1)

<class 'numpy.ndarray'> [ 77  82  21  52  52 115]

10. Write a Pandas program to convert Series of lists to one Series.

In [466]:
s2=pd.Series([['Red','Blue','Green'],['Green','Yellow'],['Orange']])
s2
s2=s2.explode(ignore_index=True)
s2

0       Red
1      Blue
2     Green
3     Green
4    Yellow
5    Orange
dtype: object

11. Write a Pandas program to sort a given Series.

In [467]:
s1=pd.Series([100,'101','python',-32,84.67])
s1.astype(str).sort_values()

3       -32
0       100
1       101
4     84.67
2    python
dtype: object

12. Write a Pandas program to add some data to an existing Series.

In [468]:
pd.concat([s1,pd.Series(['array',34])],ignore_index=True)

0       100
1       101
2    python
3       -32
4     84.67
5     array
6        34
dtype: object

13. Write a Pandas program to create a subset of a given series based on value and condition

In [469]:
s2[s2.str.len()>5]

4    Yellow
5    Orange
dtype: object

14. Write a Pandas program to change the order of index of a given series.

In [470]:
s2.sample(s2.size) #to change in specific order use s2.reindex(['idx order']) or just locate the dff o

4    Yellow
5    Orange
1      Blue
2     Green
3     Green
0       Red
dtype: object

15. Write a Pandas program to create the mean and standard deviation of the data of a
given Series.

In [471]:
s=pd.Series(np.random.randint(1,20,50))
print(s.mean(),s.median(),round(s.std(),2))

10.04 9.0 5.8

16. Write a Pandas program to get the items of a given series not present in another given
series.

In [472]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([2,4,6,8,10])
s1[~s1.isin(s2)]

0    1
2    3
4    5
dtype: int64

17. Write a Pandas program to get the items which are not common of two given series.

In [473]:
# pd.concat([s1[~s1.isin(s2)],s2[~s2.isin(s1)]])
pd.concat([s1,s2],ignore_index=True).drop_duplicates(keep=False)

0     1
2     3
4     5
7     6
8     8
9    10
dtype: int64

18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and
maximum of a given series.

In [474]:
q1,q3=np.percentile(s1,[25,75])
print(s1.min(),q1,s1.median(),q3,s1.max())

1 2.0 3.0 4.0 5

19. Write a Pandas program to calculate the frequency counts of each unique value of a
given series.

In [475]:
s1.value_counts()

1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64

20. Write a Pandas program to display most frequent value in a given series and replace
everything else as 'Other' in the series.

In [476]:
s1=pd.Series([1,2,3,4,5,5,6,5,6,6,6,7,7,7,7,7,7])
# s1.value_counts().head(2)
s1mode=s1.mode()[0]
s1.where(s1==s1mode,'Other')

0     Other
1     Other
2     Other
3     Other
4     Other
5     Other
6     Other
7     Other
8     Other
9     Other
10    Other
11        7
12        7
13        7
14        7
15        7
16        7
dtype: object

21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a
given series.

In [477]:
s1=pd.Series([1,2,5,6,7,10,11,12,15,16,19,20])
s1[s1%5==0].index

Index([2, 5, 8, 11], dtype='int64')

22. Write a Pandas program to extract items at given positions of a given series.

In [478]:
s1[[2,5,8,11]]

2      5
5     10
8     15
11    20
dtype: int64

23. Write a Pandas program to get the positions of items of a given series in another
given series.

In [479]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([1,3,5,7,10])
s1[s1.isin(s2)].index

Index([0, 2, 4, 6, 9], dtype='int64')

24. Write a Pandas program convert the first and last character of each word to upper
case in each word of a given series.

In [480]:
s=pd.Series(['python','pandas','numpy','java','php'])
s=s.str[:-1].str.title()+s.str[-1].str.upper()
s
#

0    PythoN
1    PandaS
2     NumpY
3      JavA
4       PhP
dtype: object

25. Write a Pandas program to calculate the number of characters in each word in a given
series.

In [481]:
s.str.len()

0    6
1    6
2    5
3    4
4    3
dtype: int64

26. Write a Pandas program to compute difference of differences between consecutive
numbers of a given series.

In [482]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s1.diff().diff()

0    NaN
1    NaN
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
dtype: float64

27. Write a Pandas program to convert a series of date strings to a timeseries.

In [483]:
s1=pd.Series(["01 Jan 2015","10-02-2016","20180307","2014/05/06","2016-04-12","2019-04-06T11:20"])
s1=pd.to_datetime(s1,format='mixed')
s1

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

28. Write a Pandas program to get the day of month, day of year, week number and day
of week from a given series of date strings.

In [484]:
print(s1.dt.day.to_list())
print(s1.dt.day_of_year.to_list())
print(s1.dt.isocalendar().week.to_list())
print(s1.dt.day_name().to_list())

[1, 2, 7, 6, 12, 6]
[1, 276, 66, 126, 103, 96]
[1, 39, 10, 19, 15, 14]
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']

29. Write a Pandas program to convert year-month string to dates adding a specified day
of the month.

In [485]:
s1=pd.Series(['Jan 2015','Feb 2016','Mar 2017','Apr 2018','May 2019'])
pd.to_datetime('11'+s1)

0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

30. Write a Pandas program to filter words from a given series that contain atleast two
vowels.

In [486]:
s=pd.Series(['python','pandas','numpy','java','php'])
s[s.str.count(r'[aeiouAEIOU]')>=2]

1    pandas
3      java
dtype: object

31. Write a Pandas program to compute the Euclidean distance between two given series.
Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line
distance between two points in Euclidean space. With this distance, Euclidean space
becomes a metric space. The associated norm is called the Euclidean norm

In [487]:
s1=pd.Series(np.random.randint(1,50,12))
s2=pd.Series(np.random.randint(1,50,12))
def EuclidDist(s1,s2):
    return sum((s1-s2)**2)**0.5
print(EuclidDist(s1,s2))

62.49799996799898

32. Write a Pandas program to find the positions of the values neighboured by smaller
values on both sides in a given series.

In [488]:
s=pd.Series([1,8,7,5,6,5,3,4,7,1])
s[(s>s.shift(1))&(s>s.shift(-1))].to_list()

[8, 6, 7]

33. Write a Pandas program to replace missing white spaces in a given string with the
least frequent character.

In [489]:
string='abc def abcdef icd'
s1=pd.Series(list(string))
least=s1.value_counts().index[-1]
''.join(s1.replace(' ',least))

'abcidefiabcdefiicd'

34. Write a Pandas program to compute the autocorrelations of a given numeric series.
From Wikipedia:
Autocorrelation, also known as serial correlation, is the correlation of a signal with a
delayed copy of itself as a function of delay. Informally, it is the similarity between
observations as a function of the time lag between them.

In [490]:
s = pd.Series([10, 12, 14.5, 16.5, 19, 21.2, 23.5, 26, 28.5, 31])
s.autocorr(lag=1)

0.9996187017705784

35. Write a Pandas program to create a TimeSeries to display all the Sundays of given
year.

In [491]:
pd.date_range(start=f'{'2026'}-01-01', end=f'{'2026'}-12-31', freq='W-SUN')

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08', '2026-02-15', '2026-02-22',
               '2026-03-01', '2026-03-08', '2026-03-15', '2026-03-22',
               '2026-03-29', '2026-04-05', '2026-04-12', '2026-04-19',
               '2026-04-26', '2026-05-03', '2026-05-10', '2026-05-17',
               '2026-05-24', '2026-05-31', '2026-06-07', '2026-06-14',
               '2026-06-21', '2026-06-28', '2026-07-05', '2026-07-12',
               '2026-07-19', '2026-07-26', '2026-08-02', '2026-08-09',
               '2026-08-16', '2026-08-23', '2026-08-30', '2026-09-06',
               '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04',
               '2026-10-11', '2026-10-18', '2026-10-25', '2026-11-01',
               '2026-11-08', '2026-11-15', '2026-11-22', '2026-11-29',
               '2026-12-06', '2026-12-13', '2026-12-20', '2026-12-27'],
              dtype='datetime64[ns]', freq='W-SUN')

36. Write a Pandas program to convert given series into a dataframe with its index as
another column on the dataframe.

In [492]:
s = pd.Series([10, 12, 14.5, 16.5, 19],index=['A','B','C','D','E'])
s.reset_index()

  index     0
0     A  10.0
1     B  12.0
2     C  14.5
3     D  16.5
4     E  19.0

37. Write a Pandas program to stack two given series vertically and horizontally

In [493]:
s1 = pd.Series([10, 12, 14.5, 16.5, 19])
s2=pd.Series(['A','B','C','D','E'])
pd.concat([s1,s2],ignore_index=True)

0    10.0
1    12.0
2    14.5
3    16.5
4    19.0
5       A
6       B
7       C
8       D
9       E
dtype: object

38. Write a Pandas program to check the equality of two given series.

In [494]:
s1=pd.Series(np.random.randint(1,5,6))
s2=pd.Series(np.random.randint(1,5,6))
s1==s2

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

39. Write a Pandas program to find the index of the first occurrence of the smallest and
largest value of a given series.

In [495]:
s = pd.Series([10, 12, 5,14.5, 16.5,5, 19, 21.2, 23.5, 26, 28.5, 31,31])
# print(s.idxmin(),s.idxmax())
print(list(s).index(s.min()))
print(list(s).index(s.max()))

2
11

40. Write a Pandas program to check inequality over the index axis of a given dataframe
and a given series.

In [496]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 2, 7, 4],
    'C': [1, 8, 3, 9]
})
s=pd.Series([1,2,3,4])
df.ne(s, axis=0)

       A      B      C
0  False   True  False
1  False  False   True
2  False   True  False
3  False  False   True