In [9]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from tqdm import tqdm
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.model_selection import StratifiedKFold,cross_val_score
from sklearn.ensemble import GradientBoostingClassifier
import warnings
warnings.filterwarnings("ignore")

In [10]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Vehicle Silhouettes\Vehicle.csv")
df.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [11]:
X,y=df.drop('Class',axis=1),df['Class']
le=LabelEncoder()
le_y=le.fit_transform(y)
kfold=StratifiedKFold(n_splits=5,shuffle=True,random_state=26)
gbm=GradientBoostingClassifier(random_state=26)

## Accuracy Scores of each Folds

In [13]:
results=cross_val_score(gbm,X,le_y,cv=kfold) # default scoring='accuracy_score'
results

array([0.77058824, 0.76923077, 0.78698225, 0.78106509, 0.75147929])

In [ ]:
import numpy as np
from tqdm import tqdm
from sklearn.ensemble import GradientBoostingRegressor
learning_rate=np.linspace(0.1,0.9,10)
max_depth=[None,2,3,4]
n_estimators=[25,50,100]
scores=[]

for l in tqdm(learning_rate):
    for m in max_depth:
        for n in n_estimators:
            gbc=GradientBoostingClassifier(random_state=26,learning_rate=l,max_depth=m,n_estimators=n)
            results=cross_val_score(gbm,X,le_y,cv=kfold,scoring='neg_log_loss') # default scoring='accuracy_score'
            scores.append([l,m,n,results.mean()])
df_scores=pd.DataFrame(scores,columns=['Learning_Rate','Max_Depth','N_Estimators','fold_best_log_loss'])
df_scores.sort_values(by='fold_best_log_loss',ascending= False)

In [18]:
df_scores.sort_values(by='fold_best_log_loss',ascending= False)

     Learning_Rate  Max_Depth  N_Estimators  fold_best_log_loss
0              0.1        NaN            25           -0.479198
1              0.1        NaN            50           -0.479198
2              0.1        NaN           100           -0.479198
3              0.1        2.0            25           -0.479198
4              0.1        2.0            50           -0.479198
..             ...        ...           ...                 ...
115            0.9        3.0            50           -0.479198
116            0.9        3.0           100           -0.479198
117            0.9        4.0            25           -0.479198
118            0.9        4.0            50           -0.479198
119            0.9        4.0           100           -0.479198

[120 rows x 4 columns]

In [20]:
solvers = ['lbfgs', 'saga', 'sag', 'newton-cg', 'newton-cholesky']
from tqdm import tqdm
from sklearn.ensemble import GradientBoostingRegressor

scores=[]

for l in tqdm(solvers):
    lr=LogisticRegression(solver=l)
    results=cross_val_score(lr,X,le_y,cv=kfold,scoring='neg_log_loss') # default scoring='accuracy_score'
    scores.append([l,results.mean()])
df_scores=pd.DataFrame(scores,columns=['Solvers','log_loss'])
df_scores.sort_values(by='log_loss',ascending=False)

100%|██████████| 5/5 [00:05<00:00,  1.02s/it]

           Solvers  log_loss
3        newton-cg -0.416957
4  newton-cholesky -0.438304
0            lbfgs -0.679773
2              sag -0.764177
1             saga -0.847965

In [24]:
solvers = ['lbfgs', 'saga', 'sag', 'newton-cg', 'newton-cholesky']
from tqdm import tqdm
from sklearn.ensemble import GradientBoostingRegressor
Cs=np.linspace(0.01,3,5)
scores=[]

for l in tqdm(solvers):
    for c in Cs:
        lr=LogisticRegression(solver=l,C=c)
        results=cross_val_score(lr,X,le_y,cv=kfold,scoring='neg_log_loss') # default scoring='accuracy_score'
        scores.append([l,c,results.mean()])
df_scores=pd.DataFrame(scores,columns=['Solvers','C_value','log_loss'])
df_scores.sort_values(by='log_loss',ascending=False)

100%|██████████| 5/5 [00:22<00:00,  4.40s/it]

            Solvers  C_value  log_loss
16        newton-cg   0.7575 -0.414607
17        newton-cg   1.5050 -0.421581
18        newton-cg   2.2525 -0.427825
19        newton-cg   3.0000 -0.431223
21  newton-cholesky   0.7575 -0.432451
22  newton-cholesky   1.5050 -0.447914
23  newton-cholesky   2.2525 -0.458194
24  newton-cholesky   3.0000 -0.465749
20  newton-cholesky   0.0100 -0.470541
15        newton-cg   0.0100 -0.472532
1             lbfgs   0.7575 -0.670045
3             lbfgs   2.2525 -0.676708
4             lbfgs   3.0000 -0.679349
2             lbfgs   1.5050 -0.680220
0             lbfgs   0.0100 -0.695260
12              sag   1.5050 -0.764137
13              sag   2.2525 -0.764146
11              sag   0.7575 -0.764226
14              sag   3.0000 -0.764229
10              sag   0.0100 -0.766398
6              saga   0.7575 -0.847979
8              saga   2.2525 -0.848035
7              saga   1.5050 -0.848077
9              saga   3.0000 -0.848111
5              saga   0.0100 -0.849218