In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\student_performance\student_dataset_10000_rows.csv")

In [3]:
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [4]:
X,y=df.drop('placement_status',axis=1),df['placement_status']

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [6]:
model=LogisticRegression()

In [7]:
model.fit(X_train,y_train)

LogisticRegression()

In [8]:
y_pred=model.predict(X_test)
print('Accuracy Score-->',accuracy_score(y_test,y_pred))

Accuracy Score--> 0.9993333333333333

In [9]:
import sklearn
sklearn.__version__

'1.9.1'

In [10]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Kyphosis\Kyphosis.csv")

In [11]:
df.head()

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [12]:
X,y=df.drop('Kyphosis',axis=1),df['Kyphosis']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [13]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [14]:
y_pred=model.predict(X_test)
print('Accuracy Score-->',accuracy_score(y_test,y_pred))

Accuracy Score--> 0.88

In [15]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\human-resources-analytics\HR_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low

In [16]:
X,y=df.drop('left',axis=1),df['left']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_selector,make_column_transformer

encoder=OneHotEncoder(sparse_output=False, drop='first')
ct=make_column_transformer((encoder,make_column_selector(dtype_include='object')),
                          ('passthrough',make_column_selector(dtype_include='number')),
                           verbose_feature_names_out=False
                          )

In [18]:
solvers = ['lbfgs', 'liblinear', 'saga', 'sag', 'newton-cg', 'newton-cholesky']
scores=[]
for s in solvers:
    lr=LogisticRegression(solver=s)
    pipe=Pipeline([('OHE',ct),('LR',lr)])
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append([s,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['Solver','Accuracy'])
df_score.sort_values('Accuracy',ascending=False)

C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

            Solver  Accuracy
0            lbfgs  0.800178
5  newton-cholesky  0.793065
4        newton-cg  0.793065
1        liblinear  0.792843
2             saga  0.760613
3              sag  0.753056

In [19]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Image_Segmentation\Image_Segmentation.csv")
df.sample(5)

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
75,FOLIAGE,68,103,9,0.0,0.000000,0.666667,0.577778,1.111111,0.962963,2.148148,0.111111,5.666666,0.666667,-6.111111,10.555555,-4.444445,5.666666,0.987654,-2.185466
203,GRASS,237,191,9,0.0,0.000000,1.000000,0.311111,1.500000,1.011111,7.333334,5.333334,5.444445,11.222222,-6.000000,-5.666666,11.666667,11.222222,0.535820,2.122422
71,FOLIAGE,41,75,9,0.0,0.111111,15.388889,19.136257,26.611113,31.713590,55.000000,47.444443,65.444440,52.111110,-22.666666,31.333334,-8.666667,65.444440,0.297802,-2.356754
153,PATH,219,176,9,0.0,0.111111,2.111112,1.857917,5.111111,2.841493,60.296295,53.333332,75.666670,51.888890,-20.888890,46.111110,-25.222221,75.666670,0.314462,-2.030648
48,SKY,93,29,9,0.0,0.000000,1.222224,1.229636,1.388891,1.574082,128.481480,119.000000,142.777770,123.666664,-28.444445,42.888890,-14.444445,142.777770,0.166484,-2.297760

In [20]:
X,y=df.drop('Class',axis=1),df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [ ]:
import numpy as np
solvers = ['lbfgs', 'saga', 'sag', 'newton-cg', 'newton-cholesky']
cs=np.linspace(0.001,10,20)
for s in solvers:
    for c in cs:
        lr=LogisticRegression(solver=s)
        lr.fit(X_train,y_train)
        y_pred=lr.predict(X_test)
        scores.append([s,c,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['Solver','C','Accuracy'])

In [24]:
df_score.sort_values('Accuracy',ascending=False)

              Solver         C  Accuracy
93         newton-cg  3.684842  0.920635
92         newton-cg  3.158579  0.920635
91         newton-cg  2.632316  0.920635
90         newton-cg  2.106053  0.920635
102        newton-cg  8.421211  0.920635
..               ...       ...       ...
1          liblinear  0.792843       NaN
2               saga  0.760613       NaN
3                sag  0.753056       NaN
4          newton-cg  0.793065       NaN
5    newton-cholesky  0.793065       NaN

[126 rows x 3 columns]