In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [100]:
df=pd.read_csv(r'../../Datasets\housing.csv')
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB

In [102]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

X_numeric=df.drop(columns=['price']).select_dtypes('number')
X_encoded=encoder.fit_transform(df.select_dtypes('object'))

X=pd.concat([X_numeric,X_encoded],axis=1)
y=df['price']
X

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,5850,3,1,2,1,1.0,0.0,1.0,0.0,0.0,0.0
1,4000,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
2,3060,3,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
3,6650,3,1,2,0,1.0,1.0,0.0,0.0,0.0,0.0
4,6360,2,1,1,0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
541,4800,3,2,4,0,1.0,1.0,0.0,0.0,1.0,0.0
542,6000,3,2,4,0,1.0,0.0,0.0,0.0,1.0,0.0
543,6000,3,2,4,1,1.0,1.0,0.0,0.0,1.0,0.0
544,6000,3,2,2,1,1.0,1.0,0.0,0.0,1.0,0.0
545,6000,3,1,2,1,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=26)

In [104]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [105]:
ypred=model.predict(X_test)

In [106]:
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score
print('Mean Squared Error: ',mean_squared_error(y_test,ypred))
print('Root Mean Squared Error: ',root_mean_squared_error(y_test,ypred))
print('R^2 Score: ',r2_score(y_test,ypred))

Mean Squared Error:  233765612.63451448
Root Mean Squared Error:  15289.395430641282
R^2 Score:  0.6764893122926295

In [107]:
# Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_poly

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,...,fullbase_yes^2,fullbase_yes gashw_yes,fullbase_yes airco_yes,fullbase_yes prefarea_yes,gashw_yes^2,gashw_yes airco_yes,gashw_yes prefarea_yes,airco_yes^2,airco_yes prefarea_yes,prefarea_yes^2
0,5850.0,3.0,1.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4000.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3060.0,3.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6650.0,3.0,1.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6360.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,4800.0,3.0,2.0,4.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
542,6000.0,3.0,2.0,4.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
543,6000.0,3.0,2.0,4.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
544,6000.0,3.0,2.0,2.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
545,6000.0,3.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [108]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=26)

In [109]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [110]:
ypred=model.predict(X_test)

In [111]:
print('Mean Squared Error: ',mean_squared_error(y_test,ypred))
print('Root Mean Squared Error: ',root_mean_squared_error(y_test,ypred))
print('R^2 Score: ',r2_score(y_test,ypred))

Mean Squared Error:  233765612.63451448
Root Mean Squared Error:  15289.395430641282
R^2 Score:  0.6764893122926295