In [38]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings("ignore")

In [39]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Vehicle Silhouettes\Vehicle.csv")
df.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [40]:
X,y=df.drop('Class',axis=1),df['Class']
le = LabelEncoder()
y_encoded = le.fit_transform(y)
X_train,X_test,y_train,y_test=train_test_split(X,y_encoded,test_size=0.3,random_state=26,stratify=y)

In [41]:
nb=GaussianNB()
lr=LogisticRegression()
dtc=DecisionTreeClassifier()
lda=LinearDiscriminantAnalysis()
gbc=GradientBoostingClassifier()
stk=StackingClassifier(estimators=[('NB',nb),('LR',lr),('DTC',dtc),('LDA',lda)],final_estimator=gbc)
stk.fit(X_train,y_train)

StackingClassifier(estimators=[('NB', GaussianNB()),
                               ('LR', LogisticRegression()),
                               ('DTC', DecisionTreeClassifier()),
                               ('LDA', LinearDiscriminantAnalysis())],
                   final_estimator=GradientBoostingClassifier())

In [42]:
y_pred=stk.predict(X_test)
accuracy_score(y_test,y_pred)

0.7716535433070866

In [43]:
#  using passthrough option
stk=StackingClassifier(estimators=[('DTC',dtc),('LR',lr),('LDA',lda),('NB',nb)],final_estimator=gbc,passthrough=True)
stk.fit(X_train,y_train)

StackingClassifier(estimators=[('DTC', DecisionTreeClassifier()),
                               ('LR', LogisticRegression()),
                               ('LDA', LinearDiscriminantAnalysis()),
                               ('NB', GaussianNB())],
                   final_estimator=GradientBoostingClassifier(),
                   passthrough=True)

In [44]:
y_pred=stk.predict(X_test)
accuracy_score(y_test,y_pred)

0.7952755905511811

In [45]:
# using XGBRegressor
from xgboost import XGBClassifier
xgbr=XGBClassifier(random_state=26)

stk=StackingClassifier(estimators=[('DTC',dtc),('LR',lr),('LDA',lda),('NB',nb)],final_estimator=xgbr)
stk.fit(X_train,y_train)

StackingClassifier(estimators=[('DTC', DecisionTreeClassifier()),
                               ('LR', LogisticRegression()),
                               ('LDA', LinearDiscriminantAnalysis()),
                               ('NB', GaussianNB())],
                   final_estimator=XGBClassifier(base_score=None, booster=None,
                                                 callbacks=None,
                                                 colsample_bylevel=None,
                                                 colsample_bynode=None,
                                                 colsample_bytree=None,
                                                 device=None,
                                                 early_stopping_rounds=None,
                                                 enable_categorical=T...
                                                 feature_weights=None,
                                                 gamma=None, grow_policy=None,
                                                 importance_type=None,
                                                 interaction_constraints=None,
                                                 learning_rate=None,
                                                 max_bin=None,
                                                 max_cat_threshold=None,
                                                 max_cat_to_onehot=None,
                                                 max_delta_step=None,
                                                 max_depth=None,
                                                 max_leaves=None,
                                                 min_child_weight=None,
                                                 missing=nan,
                                                 monotone_constraints=None,
                                                 multi_strategy=None,
                                                 n_estimators=None, n_jobs=None,
                                                 num_parallel_tree=None, ...))

In [46]:
y_pred=stk.predict(X_test)
accuracy_score(y_test,y_pred)

0.7755905511811023

In [47]:
xgbr=XGBClassifier(random_state=26)

stk=StackingClassifier(estimators=[('DTC',dtc),('LR',lr),('LDA',lda),('NB',nb)],final_estimator=xgbr,passthrough=True)
stk.fit(X_train,y_train)

StackingClassifier(estimators=[('DTC', DecisionTreeClassifier()),
                               ('LR', LogisticRegression()),
                               ('LDA', LinearDiscriminantAnalysis()),
                               ('NB', GaussianNB())],
                   final_estimator=XGBClassifier(base_score=None, booster=None,
                                                 callbacks=None,
                                                 colsample_bylevel=None,
                                                 colsample_bynode=None,
                                                 colsample_bytree=None,
                                                 device=None,
                                                 early_stopping_rounds=None,
                                                 enable_categorical=T...
                                                 gamma=None, grow_policy=None,
                                                 importance_type=None,
                                                 interaction_constraints=None,
                                                 learning_rate=None,
                                                 max_bin=None,
                                                 max_cat_threshold=None,
                                                 max_cat_to_onehot=None,
                                                 max_delta_step=None,
                                                 max_depth=None,
                                                 max_leaves=None,
                                                 min_child_weight=None,
                                                 missing=nan,
                                                 monotone_constraints=None,
                                                 multi_strategy=None,
                                                 n_estimators=None, n_jobs=None,
                                                 num_parallel_tree=None, ...),
                   passthrough=True)

In [48]:
y_pred=stk.predict(X_test)
accuracy_score(y_test,y_pred)

0.7913385826771654

In [49]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import StackingRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor

In [50]:
df= pd.read_csv(r"E:\DataAnalytics\Cases\Medical_Cost_Personal\insurance.csv")
df.sample(5)

      age     sex     bmi  children smoker     region      charges
555    28    male  23.800         2     no  southwest   3847.67400
1047   22    male  52.580         1    yes  southeast  44501.39820
308    58    male  34.865         0     no  northeast  11944.59435
1034   61    male  38.380         0     no  northwest  12950.07120
1073   54  female  28.880         2     no  northeast  12096.65120

In [51]:
X, y = df.drop('charges', axis=1), df['charges']
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.3, random_state=26)

In [52]:
scaler= StandardScaler()
encoder= OneHotEncoder(sparse_output=False, drop='first')
ct= make_column_transformer((encoder, make_column_selector(dtype_include='object')),
                            ('passthrough', make_column_selector(dtype_include='number')),
                            verbose_feature_names_out=False).set_output(transform='pandas')

In [64]:
lr= LinearRegression()
knn_pipe= Pipeline([('SCL', scaler), ('KNN', KNeighborsRegressor())])
ridge=Ridge()
lasso= Lasso()
dtr= DecisionTreeRegressor()
gbm= GradientBoostingRegressor()
stack= StackingRegressor(estimators= [('Tree', dtr), ('LR', lr), ('RIDGE', ridge), ('LASSO', lasso), ('KNN', knn_pipe)],
                         final_estimator= gbm, passthrough=True)
pipe= Pipeline([('CT', ct), ('STACK', stack)])
pipe.fit(X_train, y_train)

Pipeline(steps=[('CT',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000021C1E205090>),
                                                 ('passthrough', 'passthrough',
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000021C1E0E5220>)],
                                   verbose_feature_names_out=False)),
                ('STACK',
                 StackingRegressor(estimators=[('Tree',
                                                DecisionTreeRegressor()),
                                               ('LR', LinearRegression()),
                                               ('RIDGE', Ridge()),
                                               ('LASSO', Lasso()),
                                               ('KNN',
                                                Pipeline(steps=[('SCL',
                                                                 StandardScaler()),
                                                                ('KNN',
                                                                 KNeighborsRegressor())]))],
                                   final_estimator=GradientBoostingRegressor(),
                                   passthrough=True))])

In [61]:
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8562504024012124

In [65]:
stack=StackingRegressor(estimators=[('Tree', dtr), ('LR', lr), ('RIDGE', ridge), ('LASSO', lasso), ('KNN', knn_pipe)],
                        final_estimator=gbm)
pipe= Pipeline([('CT', ct), ('STACK',stack)])
pipe.fit(X_train, y_train)

Pipeline(steps=[('CT',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000021C1E205090>),
                                                 ('passthrough', 'passthrough',
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000021C1E0E5220>)],
                                   verbose_feature_names_out=False)),
                ('STACK',
                 StackingRegressor(estimators=[('Tree',
                                                DecisionTreeRegressor()),
                                               ('LR', LinearRegression()),
                                               ('RIDGE', Ridge()),
                                               ('LASSO', Lasso()),
                                               ('KNN',
                                                Pipeline(steps=[('SCL',
                                                                 StandardScaler()),
                                                                ('KNN',
                                                                 KNeighborsRegressor())]))],
                                   final_estimator=GradientBoostingRegressor()))])

In [66]:
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8533369594616416