In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer,make_column_selector
from tqdm import tqdm

In [2]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Vehicle Silhouettes\Vehicle.csv")
df.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [5]:
X,y=df.drop('Class',axis=1),df.Class
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [6]:
import numpy as np
cs=np.linspace(0.001, 10,20)
scaler=StandardScaler()
scores=[]
dfs=['ovo','ovr']
for c in tqdm(cs):
    for f in dfs:
        svm=SVC(kernel="linear",C=c,decision_function_shape=f)
        pipe=Pipeline([('SCL',scaler),('SVC',svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,f,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['C_values','Decision','Accuracy'])
df_score.sort_values('Accuracy',ascending=False)

100%|██████████| 20/20 [00:01<00:00, 14.41it/s]

     C_values Decision  Accuracy
11   2.632316      ovr  0.807087
10   2.632316      ovo  0.807087
14   3.684842      ovo  0.807087
15   3.684842      ovr  0.807087
9    2.106053      ovr  0.807087
8    2.106053      ovo  0.807087
6    1.579789      ovo  0.803150
7    1.579789      ovr  0.803150
24   6.316158      ovo  0.803150
25   6.316158      ovr  0.803150
18   4.737368      ovo  0.803150
19   4.737368      ovr  0.803150
20   5.263632      ovo  0.803150
21   5.263632      ovr  0.803150
13   3.158579      ovr  0.803150
12   3.158579      ovo  0.803150
16   4.211105      ovo  0.803150
17   4.211105      ovr  0.803150
22   5.789895      ovo  0.803150
23   5.789895      ovr  0.803150
26   6.842421      ovo  0.799213
27   6.842421      ovr  0.799213
28   7.368684      ovo  0.795276
29   7.368684      ovr  0.795276
32   8.421211      ovo  0.791339
33   8.421211      ovr  0.791339
34   8.947474      ovo  0.791339
35   8.947474      ovr  0.791339
36   9.473737      ovo  0.791339
37   9.473737      ovr  0.791339
30   7.894947      ovo  0.791339
31   7.894947      ovr  0.791339
38  10.000000      ovo  0.791339
39  10.000000      ovr  0.791339
5    1.053526      ovr  0.787402
4    1.053526      ovo  0.787402
3    0.527263      ovr  0.779528
2    0.527263      ovo  0.779528
1    0.001000      ovr  0.425197
0    0.001000      ovo  0.425197

## Radial Bias Function as Kernel

In [9]:
import numpy as np
cs=np.linspace(0.001, 10,20)
gs=np.linspace(0.1,10,20)
scaler=StandardScaler()
scores=[]
dfs=['ovo','ovr']
for c in tqdm(cs):
    for f in dfs:
        for g in gs:
            svm=SVC(kernel="rbf",C=c,gamma=g,decision_function_shape=f)
            pipe=Pipeline([('SCL',scaler),('SVC',svm)])
            pipe.fit(X_train,y_train)
            y_pred=pipe.predict(X_test)
            scores.append([c,f,g,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['C_values','Gamma_Values','Decision','Accuracy'])
df_score.sort_values('Accuracy',ascending=False)

100%|██████████| 20/20 [00:38<00:00,  1.91s/it]

     C_values Gamma_Values  Decision  Accuracy
380  4.737368          ovr  0.100000  0.803150
360  4.737368          ovo  0.100000  0.803150
340  4.211105          ovr  0.100000  0.799213
280  3.684842          ovo  0.100000  0.799213
420  5.263632          ovr  0.100000  0.799213
..        ...          ...       ...       ...
4    0.001000          ovo  2.184211  0.255906
3    0.001000          ovo  1.663158  0.255906
2    0.001000          ovo  1.142105  0.255906
1    0.001000          ovo  0.621053  0.255906
0    0.001000          ovo  0.100000  0.255906

[800 rows x 4 columns]