In [1]:
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tqdm in C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages (4.70.1)
Requirement already satisfied: colorama in C:\Users\PGCP-AI\AppData\Roaming\Python\Python314\site-packages (from tqdm) (0.4.6)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer,make_column_selector
from tqdm import tqdm

In [3]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\student_performance\student_dataset_10000_rows.csv")
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [4]:
X,y=df.drop('placement_status',axis=1),df['placement_status']

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [6]:
svm=SVC(kernel="linear")

In [7]:
svm.fit(X_train,y_train)

SVC(kernel='linear')

In [8]:
y_pred=svm.predict(X_test)
accuracy_score(y_test,y_pred)

0.9993333333333333

# Excercise

In [9]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\human-resources-analytics\HR_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low

In [10]:
X,y=df.drop('left',axis=1),df['left']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [11]:
ohe=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
scaler=StandardScaler()
ct=make_column_transformer(
    (ohe,make_column_selector(dtype_include='object')),
    ('passthrough',make_column_selector(dtype_include='number')),
    verbose_feature_names_out=False
)
svm=SVC(kernel="linear")
pipe=Pipeline([('OHE',ct),('SCL',scaler),('SVC',svm)])
pipe.fit(X_train,y_train)

Pipeline(steps=[('OHE',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000002660491DBE0>),
                                                 ('passthrough', 'passthrough',
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000026604853B10>)],
                                   verbose_feature_names_out=False)),
                ('SCL', StandardScaler()), ('SVC', SVC(kernel='linear'))])

In [12]:
y_pred=pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.7781729273171816

In [13]:
import numpy as np
cs=np.linspace(0.001, 10,20)
scores=[]
for c in tqdm(cs):
    svm=SVC(kernel="linear",C=c)
    pipe=Pipeline([('OHE',ct),('SCL',scaler),('SVC',svm)])
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append([c,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['C_values','Accuracy'])
df_score.sort_values('Accuracy',ascending=False)

100%|██████████| 20/20 [03:19<00:00,  9.96s/it]

     C_values  Accuracy
1    0.527263  0.778395
2    1.053526  0.778173
3    1.579789  0.778173
4    2.106053  0.778173
12   6.316158  0.778173
5    2.632316  0.778173
6    3.158579  0.778173
7    3.684842  0.778173
8    4.211105  0.778173
9    4.737368  0.778173
10   5.263632  0.778173
11   5.789895  0.778173
16   8.421211  0.778173
13   6.842421  0.778173
14   7.368684  0.778173
15   7.894947  0.778173
18   9.473737  0.778173
17   8.947474  0.778173
19  10.000000  0.778173
0    0.001000  0.762169

In [14]:
cs=np.linspace(0.001, 10,20)
scores=[]
for c in tqdm(cs):
    for d in range(2,5):
        svm=SVC(kernel="poly",C=c,degree=d)
        pipe=Pipeline([('OHE',ct),('SCL',scaler),('SVC',svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,d,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['C_values','Degree','Accuracy'])
df_score.sort_values('Accuracy',ascending=False).head()

100%|██████████| 20/20 [01:37<00:00,  4.86s/it]

     C_values  Degree  Accuracy
56   9.473737       4  0.959102
53   8.947474       4  0.959102
59  10.000000       4  0.958880
50   8.421211       4  0.958435
47   7.894947       4  0.957991

# Kernel is Rbf

In [15]:
cs=np.linspace(0.001, 10,20)
# gs=np.linspace(0.001, 10,20)
scores=[]
for c in tqdm(cs):
    for g in gs:
        svm=SVC(kernel="poly",C=c)
        pipe=Pipeline([('OHE',ct),('SCL',scaler),('SVC',svm)])
        pipe.fit(X_train,y_train)
        y_pred=pipe.predict(X_test)
        scores.append([c,g,accuracy_score(y_test,y_pred)])
df_score=pd.DataFrame(scores,columns=['C_values','Gamma_values','Accuracy'])
df_score.sort_values('Accuracy',ascending=False).head()

  0%|          | 0/20 [00:00<?, ?it/s]

NameError: name 'gs' is not defined