## -----Voting Ensembling Technique-----

In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier
from tqdm import tqdm
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [39]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Wisconsin\BreastCancer.csv",index_col=0)
df.head()

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign

In [40]:
X,y=df.drop('Class',axis=1),df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=0.3,stratify=y)

In [41]:
dtc=DecisionTreeClassifier(random_state=26)
LogReg=LogisticRegression()
knn=KNeighborsClassifier()
vc=VotingClassifier([('TREE',dtc),('LOGR',LogReg),('KNN',knn)])

In [42]:
vc.fit(X_train,y_train)

VotingClassifier(estimators=[('TREE', DecisionTreeClassifier(random_state=26)),
                             ('LOGR', LogisticRegression()),
                             ('KNN', KNeighborsClassifier())])

In [43]:
y_pred=vc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

In [44]:
vc.named_estimators_

{'TREE': DecisionTreeClassifier(random_state=26),
 'LOGR': LogisticRegression(),
 'KNN': KNeighborsClassifier()}

In [45]:
vc.named_estimators_['TREE'].predict(X_test)

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [50]:
scores=[]
for d in tqdm([None,2,3,4,5,6,7,8,9]):
    for s in ['lbfgs','sag','saga','liblinear']:
        for k in [2,3,4,5,10,13,15,17,20]:
            dtc=DecisionTreeClassifier(random_state=26,max_depth=d)
            LogReg=LogisticRegression(solver=s)
            knn=KNeighborsClassifier(n_neighbors=k)
            vc=VotingClassifier([('TREE',dtc),('LOGR',LogReg),('KNN',knn)],voting='soft') 
            #default voting tech is hard which returns mostfrequent output
            #soft voting technique will average the probabilies of each class 
            vc.fit(X_train,y_train)
            y_pred=vc.predict(X_test)
            scores.append([d,s,k,accuracy_score(y_test,y_pred)])

100%|██████████| 9/9 [00:08<00:00,  1.01it/s]

In [51]:
df_scores=pd.DataFrame(scores,columns=['Depth','Solver','Neighbors','Accuracy'])
df_scores.sort_values('Accuracy',ascending=False)

     Depth     Solver  Neighbors  Accuracy
281    8.0  liblinear          4  0.971429
298    9.0        sag          3  0.971429
272    8.0       saga          4  0.971429
317    9.0  liblinear          4  0.971429
118    4.0        sag          3  0.971429
..     ...        ...        ...       ...
246    7.0  liblinear          5  0.957143
30     NaN  liblinear          5  0.957143
151    5.0      lbfgs         17  0.952381
183    6.0      lbfgs          5  0.952381
219    7.0      lbfgs          5  0.952381

[324 rows x 4 columns]

In [54]:
y_test_enc=np.where(y_test=='Malignant',1,0)
y_pred=vc.named_estimators_['TREE'].predict(X_test)
print('Tree Acc = ',accuracy_score(y_test_enc,y_pred))
y_pred=vc.named_estimators_['LOGR'].predict(X_test)
print('Logistic Acc = ',accuracy_score(y_test_enc,y_pred))
y_pred=vc.named_estimators_['KNN'].predict(X_test)
print('Knn Acc = ',accuracy_score(y_test_enc,y_pred))

Tree Acc =  0.9571428571428572
Logistic Acc =  0.9619047619047619
Knn Acc =  0.9666666666666667

# Exercise

In [101]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.ensemble import VotingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [102]:
lr=LinearRegression()
rid=Ridge()
lasso=Lasso()
tree=DecisionTreeRegressor(random_state=26)

In [103]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Concrete_Strength\Concrete_Data.csv")
df.head()

   Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

In [104]:
X,y=df.drop('Strength',axis=1),df['Strength']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=0.3)

In [105]:
vr=VotingRegressor([('LR',lr),('RIG',rid),('LASSO',lasso),('TREE',tree)])

In [106]:
vr.fit(X_train,y_train)

VotingRegressor(estimators=[('LR', LinearRegression()), ('RIG', Ridge()),
                            ('LASSO', Lasso()),
                            ('TREE', DecisionTreeRegressor(random_state=26))])

In [107]:
y_pred=vr.predict(X_test)
r2_score(y_test,y_pred)

0.7557599363240081

In [108]:
y_pred=vc.named_estimators_['LR'].predict(X_test)
print('regression R2 ',r2_score(y_test,y_pred))
y_pred=vc.named_estimators_['RIG'].predict(X_test)
print('Ridge R2 = ',r2_score(y_test,y_pred))
y_pred=vc.named_estimators_['LASSO'].predict(X_test)
print('Lasso R2 = ',r2_score(y_test,y_pred))
y_pred=vc.named_estimators_['TREE'].predict(X_test)
print('Tree r2 = ',r2_score(y_test,y_pred))

regression R2  0.6181464728464399
Ridge R2 =  0.6181470326108837
Lasso R2 =  0.6188405404462809
Tree r2 =  0.8500256114787615

In [109]:
vr=VotingRegressor([('LR',lr),('RIG',rid),('LASSO',lasso),('TREE',tree)],weights=[0.9,0.9,1,10])
vr.fit(X_train,y_train)

VotingRegressor(estimators=[('LR', LinearRegression()), ('RIG', Ridge()),
                            ('LASSO', Lasso()),
                            ('TREE', DecisionTreeRegressor(random_state=26))],
                weights=[0.9, 0.9, 1, 10])

In [110]:
y_pred=vr.predict(X_test)
r2_score(y_test,y_pred)

0.8717692447087042

# ------Booting Sampling Technique-------

In [126]:
from sklearn.ensemble import BaggingClassifier

In [127]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Wisconsin\BreastCancer.csv",index_col=0)
df.head()
X,y=df.drop('Class',axis=1),df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=0.3,stratify=y)

In [128]:
lr=LogisticRegression()
bagg=BaggingClassifier(estimator=lr,n_estimators=15,random_state=26)
bagg.fit(X_train,y_train)

BaggingClassifier(estimator=LogisticRegression(), n_estimators=15,
                  random_state=26)

In [130]:
y_pred=bagg.predict(X_test)
accuracy_score(y_test,y_pred)

0.9571428571428572

In [131]:
est=[lr,knn,dtc]
n_samples=[10,25,50]
scores=[]
for e in est:
    for n in n_samples:
        bagg=BaggingClassifier(estimator=e,n_estimators=n,random_state=26)
        bagg.fit(X_train,y_train)
        y_pred=bagg.predict(X_test)
        scores.append([e,n,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['Estimator','N','Accuracy'])

In [136]:
df_scores.sort_values('Accuracy',ascending=False)

                                           Estimator   N  Accuracy
4               KNeighborsClassifier(n_neighbors=20)  25  0.966667
7  DecisionTreeClassifier(max_depth=9, random_sta...  25  0.966667
3               KNeighborsClassifier(n_neighbors=20)  10  0.966667
6  DecisionTreeClassifier(max_depth=9, random_sta...  10  0.966667
5               KNeighborsClassifier(n_neighbors=20)  50  0.966667
8  DecisionTreeClassifier(max_depth=9, random_sta...  50  0.961905
2                               LogisticRegression()  50  0.961905
1                               LogisticRegression()  25  0.957143
0                               LogisticRegression()  10  0.952381

# Exercise -- on concreetDataset with ridge, lasso, Dtreeregressor

In [144]:
from sklearn.ensemble import BaggingRegressor

In [145]:
df=pd.read_csv(r"E:\DataAnalytics\Cases\Concrete_Strength\Concrete_Data.csv")
df.head()

   Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

In [146]:
X,y=df.drop('Strength',axis=1),df['Strength']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=0.3)

In [147]:
lr=LinearRegression()
rid=Ridge()
lasso=Lasso()
tree=DecisionTreeRegressor(random_state=26)

In [151]:
est=[lr,rid,lasso,tree]
n_samples=[10,25,50]
scores=[]
for e in est:
    for n in n_samples:
        bagg=BaggingRegressor(estimator=e,n_estimators=n,random_state=26)
        bagg.fit(X_train,y_train)
        y_pred=bagg.predict(X_test)
        scores.append([e,n,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['Estimator','N','R2_Score'])
df_scores.sort_values('R2_Score',ascending=False)

                                 Estimator   N  R2_Score
11  DecisionTreeRegressor(random_state=26)  50  0.896730
10  DecisionTreeRegressor(random_state=26)  25  0.893895
9   DecisionTreeRegressor(random_state=26)  10  0.893069
6                                  Lasso()  10  0.620327
3                                  Ridge()  10  0.619630
0                       LinearRegression()  10  0.619629
8                                  Lasso()  50  0.618218
5                                  Ridge()  50  0.617487
2                       LinearRegression()  50  0.617486
7                                  Lasso()  25  0.616078
4                                  Ridge()  25  0.615382
1                       LinearRegression()  25  0.615382