In [13]:
import pandas as pd
from sklearn.linear_model import LinearRegression,ElasticNet,Ridge,Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,root_mean_squared_error,mean_squared_error
from sklearn.preprocessing import OneHotEncoder

In [6]:
df=pd.read_csv(r'../../Datasets\housing.csv')
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [19]:
encoder=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

# X=df.drop('price',axis=1)
# X_numeric=X.select_dtypes('number')
# X_encoded=encoder.fit_transform(df.select_dtypes('object'))

# X=pd.concat([X_numeric,X_encoded],axis=1)
dum_hous=pd.get_dummies(df,drop_first=True)
dum_hous
X=dum_hous.drop('price',axis=1)
y=dum_hous['price']

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=26)

In [21]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [23]:
ypred=model.predict(X_test)
ypred

array([ 39106.04668329,  94925.58814535,  89622.24011396,  51506.53234903,
        58151.57303434, 149416.64745931,  97263.54298037,  64829.35072779,
        60673.81069879,  64045.80392407,  32955.35133112,  47511.95500877,
        48863.82254109,  41478.91863399,  90019.08216971,  44475.5598059 ,
        62772.27595251,  51472.70393703,  88227.61366678, 128812.00677426,
        45155.92556192,  51450.95079792, 111832.46008554,  99533.96952675,
        78330.87019467,  62909.79153249,  68286.74198369,  69532.50922096,
       104629.02037735,  41632.14107552,  88143.62132097,  67800.8262899 ,
        31828.61422009,  42490.29155068,  88434.34206025,  63940.1163734 ,
        48743.28110371,  54799.04309291,  52336.88110657, 116591.54178783,
        83163.05773234,  43004.03999087,  49292.60351353,  47783.26238391,
        99118.65070448,  46628.32171828, 103347.21563321,  42945.43167979,
        68811.71084109,  53730.19020773,  80323.18692378,  79357.75058179,
        31799.34035901,  31451.8155753 ,  55822.82883143, 100524.62451141,
        51699.20774226,  70676.09783679,  72960.34186494,  58832.11962446,
        83912.63453039,  62093.75683567,  41231.62456431,  60187.91357694,
        66990.26016264,  96132.86408302,  33287.24487572,  73971.04694753,
       100056.98424654,  75794.48937428,  74708.12215606, 102607.85853785,
        81804.83599123,  42719.70991512,  92886.5848927 , 106340.83510581,
        72669.57336299, 113758.76266272,  89242.91247413,  53746.57490942,
        49223.79739693,  51613.85480477,  39616.18537474,  79215.57205809,
        47042.8187989 ,  41492.15633053,  86477.80145858,  66012.90484666,
        39531.1622595 ,  88926.61937049,  78484.21201744,  31531.39498494,
        44454.89537047,  40028.41179155, 104235.60613315,  46495.63097034,
        56970.82172128,  76440.85093872,  41571.71702527,  74473.11603931,
        93043.18747221,  39701.20848998, 103499.72798884,  57421.68967188,
        38144.5403731 ,  39658.69693236,  63873.38186679, 100994.72725623,
        50826.16659301,  55159.01763104])

In [24]:
print('Mean Squared Error: ',mean_squared_error(y_test,ypred))
print('Root Mean Squared Error: ',root_mean_squared_error(y_test,ypred))
print('R^2 Score: ',r2_score(y_test,ypred))

Mean Squared Error:  233765612.63451448
Root Mean Squared Error:  15289.395430641282
R^2 Score:  0.6764893122926295

In [25]:
test_set=pd.read_csv(r'../../Datasets\tst_housing.csv')

test_set.head()

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no